# Generated by Django 4.2.7 on 2025-07-26 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_study_time', models.IntegerField(default=0)),
                ('documents_studied', models.IntegerField(default=0)),
                ('flashcards_created', models.IntegerField(default=0)),
                ('questions_asked', models.IntegerField(default=0)),
                ('most_studied_topics', models.JSONField(blank=True, default=list)),
                ('study_streak', models.IntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], default=3)),
                ('time_spent', models.IntegerField(default=0)),
                ('questions_asked', models.IntegerField(default=0)),
                ('last_studied', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='DailyStudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_time', models.IntegerField(default=0)),
                ('flashcards_reviewed', models.IntegerField(default=0)),
                ('questions_asked', models.IntegerField(default=0)),
                ('documents_accessed', models.ManyToManyField(blank=True, to='reader.document')),
                ('topics_studied', models.ManyToManyField(blank=True, to='reader.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
